# Real-Time Credit Card Fraud Detection & Risk Intelligence Platform

## Notebook 03 — Data Cleaning

### Objective

The objective of this notebook is to clean and prepare the transaction
dataset for feature engineering and machine learning.

In this notebook, we will:

- Handle missing values if present
- Remove unnecessary columns
- Identify and remove duplicate records
- Verify data consistency
- Check the final structure of the cleaned dataset
- Save the cleaned dataset for the next stage

The original raw dataset will not be modified. A separate copy will be
created for the cleaning process.

In [ ]:
import numpy as np
import pandas as pd

In [2]:
fraudTrain = pd.read_csv("fraudTrain.csv")
fraudTrain.head(1)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0

In [3]:
fraudTrain_cleaned = fraudTrain.copy()

In [6]:
fraudTrain_cleaned= fraudTrain_cleaned.drop_duplicates()

In [7]:
fraudTrain_cleaned.shape

(1296675, 23)

In [8]:
fraudTrain_cleaned.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [9]:
fraudTrain_cleaned.dtypes

Unnamed: 0                 int64
trans_date_trans_time     object
cc_num                     int64
merchant                  object
category                  object
amt                      float64
first                     object
last                      object
gender                    object
street                    object
city                      object
state                     object
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                       object
dob                       object
trans_num                 object
unix_time                  int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

In [10]:
fraudTrain_cleaned['Unnamed: 0'].head()

0    0
1    1
2    2
3    3
4    4
Name: Unnamed: 0, dtype: int64

In [12]:
fraudTrain_cleaned = fraudTrain_cleaned.drop(columns = ['Unnamed: 0'])

In [13]:
fraudTrain_cleaned['is_fraud'].unique()

array([0, 1])

In [14]:
fraudTrain_cleaned.to_csv('fraudTrain_cleaned.csv', index=False)

In [15]:
fraudTrain_cleaned.head(1)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0